base_url = "https://benquinteros.com"
title = "Ben Quinteros"
description = "Resume and portfolio"
default_language = "en"
theme = "BelResume"
build_search_index = false

[extra]
site_name = "Ben Quinteros"
